"""add columns

Revision ID: f2c4e2970395
Revises: 15e0602bba88
Create Date: 2025-01-21 13:45:27.497912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c4e2970395'
down_revision = '15e0602bba88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demand_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('demand_end_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.drop_column('demand_end_date')
        batch_op.drop_column('demand_start_date')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
